USE master
GO

CREATE LOGIN DVDLibraryApp WITH PASSWORD='Testing123'
GO

GRANT EXECUTE ON DVDByID TO DVDLibraryApp
GRANT EXECUTE ON AllDVD TO DVDLibraryApp
GRANT EXECUTE ON DVDTitle TO DVDLibraryApp
GRANT EXECUTE ON DVDReleaseYear TO DVDLibraryApp
GRANT EXECUTE ON DVDDirector TO DVDLibraryApp
GRANT EXECUTE ON DVDByRating TO DVDLibraryApp
GRANT EXECUTE ON InsertDVD TO DVDLibraryApp
GRANT EXECUTE ON DVDUpdate TO DVDLibraryApp
GRANT EXECUTE ON InsertDVD TO DVDLibraryApp
GRANT EXECUTE ON MovieDelete TO DVDLibraryApp
GO